// Code generated by go-swagger; DO NOT EDIT.

package attestationmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReportAttestationReportRequest report attestation report request
//
// swagger:model report.AttestationReportRequest
type ReportAttestationReportRequest struct {

	// node
	Node *ReportNodeInfo `json:"node,omitempty"`

	// nonce
	// Example: 884f2638c74645b859f87e76560748cc
	Nonce string `json:"nonce,omitempty"`

	// report
	Report *RestReport `json:"report,omitempty"`
}

// Validate validates this report attestation report request
func (m *ReportAttestationReportRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReport(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReportAttestationReportRequest) validateNode(formats strfmt.Registry) error {
	if swag.IsZero(m.Node) { // not required
		return nil
	}

	if m.Node != nil {
		if err := m.Node.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("node")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("node")
			}

			return err
		}
	}

	return nil
}

func (m *ReportAttestationReportRequest) validateReport(formats strfmt.Registry) error {
	if swag.IsZero(m.Report) { // not required
		return nil
	}

	if m.Report != nil {
		if err := m.Report.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("report")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("report")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this report attestation report request based on the context it is used
func (m *ReportAttestationReportRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateNode(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateReport(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReportAttestationReportRequest) contextValidateNode(ctx context.Context, formats strfmt.Registry) error {

	if m.Node != nil {

		if swag.IsZero(m.Node) { // not required
			return nil
		}

		if err := m.Node.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("node")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("node")
			}

			return err
		}
	}

	return nil
}

func (m *ReportAttestationReportRequest) contextValidateReport(ctx context.Context, formats strfmt.Registry) error {

	if m.Report != nil {

		if swag.IsZero(m.Report) { // not required
			return nil
		}

		if err := m.Report.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("report")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("report")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ReportAttestationReportRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReportAttestationReportRequest) UnmarshalBinary(b []byte) error {
	var res ReportAttestationReportRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
