// Code generated by go-swagger; DO NOT EDIT.

package attestationmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReportComponentReport report component report
//
// swagger:model report.ComponentReport
type ReportComponentReport struct {

	// evidence
	Evidence map[string]string `json:"evidence,omitempty"`

	// SHA512 of the component
	Measurement string `json:"measurement,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// pcrs
	Pcrs map[string]string `json:"pcrs,omitempty"`

	// Hex encoded TPM quote (includes nonce)
	Quote string `json:"quote,omitempty"`

	// Hex encoded TPM signature over quote
	Signature string `json:"signature,omitempty"`
}

// Validate validates this report component report
func (m *ReportComponentReport) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this report component report based on context it is used
func (m *ReportComponentReport) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReportComponentReport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReportComponentReport) UnmarshalBinary(b []byte) error {
	var res ReportComponentReport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
