// Code generated by go-swagger; DO NOT EDIT.

package attestationmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReportNodeInfo report node info
//
// swagger:model report.NodeInfo
type ReportNodeInfo struct {

	// ip
	IP string `json:"ip,omitempty"`

	// uuid
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this report node info
func (m *ReportNodeInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this report node info based on context it is used
func (m *ReportNodeInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReportNodeInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReportNodeInfo) UnmarshalBinary(b []byte) error {
	var res ReportNodeInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
