// Code generated by go-swagger; DO NOT EDIT.

package attestationmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RestComponentReport rest component report
//
// swagger:model rest.ComponentReport
type RestComponentReport struct {

	// evidence
	Evidence map[string]string `json:"evidence,omitempty"`

	// SHA512 of the component
	Measurement string `json:"measurement,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this rest component report
func (m *RestComponentReport) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rest component report based on context it is used
func (m *RestComponentReport) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RestComponentReport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestComponentReport) UnmarshalBinary(b []byte) error {
	var res RestComponentReport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
