// Code generated by go-swagger; DO NOT EDIT.

package attestation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetReportIPTrustReader is a Reader for the GetReportIPTrust structure.
type GetReportIPTrustReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetReportIPTrustReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetReportIPTrustOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetReportIPTrustBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetReportIPTrustUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetReportIPTrustNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewGetReportIPTrustMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetReportIPTrustInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /report/{ip}/trust] GetReportIPTrust", response, response.Code())
	}
}

// NewGetReportIPTrustOK creates a GetReportIPTrustOK with default headers values
func NewGetReportIPTrustOK() *GetReportIPTrustOK {
	return &GetReportIPTrustOK{}
}

/*
GetReportIPTrustOK describes a response with status code 200, with default header values.

No content
*/
type GetReportIPTrustOK struct {
	Payload string
}

// IsSuccess returns true when this get report Ip trust o k response has a 2xx status code
func (o *GetReportIPTrustOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get report Ip trust o k response has a 3xx status code
func (o *GetReportIPTrustOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get report Ip trust o k response has a 4xx status code
func (o *GetReportIPTrustOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get report Ip trust o k response has a 5xx status code
func (o *GetReportIPTrustOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get report Ip trust o k response a status code equal to that given
func (o *GetReportIPTrustOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get report Ip trust o k response
func (o *GetReportIPTrustOK) Code() int {
	return 200
}

func (o *GetReportIPTrustOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /report/{ip}/trust][%d] getReportIpTrustOK %s", 200, payload)
}

func (o *GetReportIPTrustOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /report/{ip}/trust][%d] getReportIpTrustOK %s", 200, payload)
}

func (o *GetReportIPTrustOK) GetPayload() string {
	return o.Payload
}

func (o *GetReportIPTrustOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetReportIPTrustBadRequest creates a GetReportIPTrustBadRequest with default headers values
func NewGetReportIPTrustBadRequest() *GetReportIPTrustBadRequest {
	return &GetReportIPTrustBadRequest{}
}

/*
GetReportIPTrustBadRequest describes a response with status code 400, with default header values.

If the request is invalid
*/
type GetReportIPTrustBadRequest struct {
	Payload string
}

// IsSuccess returns true when this get report Ip trust bad request response has a 2xx status code
func (o *GetReportIPTrustBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get report Ip trust bad request response has a 3xx status code
func (o *GetReportIPTrustBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get report Ip trust bad request response has a 4xx status code
func (o *GetReportIPTrustBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get report Ip trust bad request response has a 5xx status code
func (o *GetReportIPTrustBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get report Ip trust bad request response a status code equal to that given
func (o *GetReportIPTrustBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get report Ip trust bad request response
func (o *GetReportIPTrustBadRequest) Code() int {
	return 400
}

func (o *GetReportIPTrustBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /report/{ip}/trust][%d] getReportIpTrustBadRequest %s", 400, payload)
}

func (o *GetReportIPTrustBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /report/{ip}/trust][%d] getReportIpTrustBadRequest %s", 400, payload)
}

func (o *GetReportIPTrustBadRequest) GetPayload() string {
	return o.Payload
}

func (o *GetReportIPTrustBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetReportIPTrustUnauthorized creates a GetReportIPTrustUnauthorized with default headers values
func NewGetReportIPTrustUnauthorized() *GetReportIPTrustUnauthorized {
	return &GetReportIPTrustUnauthorized{}
}

/*
GetReportIPTrustUnauthorized describes a response with status code 401, with default header values.

No content
*/
type GetReportIPTrustUnauthorized struct {
	Payload string
}

// IsSuccess returns true when this get report Ip trust unauthorized response has a 2xx status code
func (o *GetReportIPTrustUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get report Ip trust unauthorized response has a 3xx status code
func (o *GetReportIPTrustUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get report Ip trust unauthorized response has a 4xx status code
func (o *GetReportIPTrustUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get report Ip trust unauthorized response has a 5xx status code
func (o *GetReportIPTrustUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get report Ip trust unauthorized response a status code equal to that given
func (o *GetReportIPTrustUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get report Ip trust unauthorized response
func (o *GetReportIPTrustUnauthorized) Code() int {
	return 401
}

func (o *GetReportIPTrustUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /report/{ip}/trust][%d] getReportIpTrustUnauthorized %s", 401, payload)
}

func (o *GetReportIPTrustUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /report/{ip}/trust][%d] getReportIpTrustUnauthorized %s", 401, payload)
}

func (o *GetReportIPTrustUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *GetReportIPTrustUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetReportIPTrustNotFound creates a GetReportIPTrustNotFound with default headers values
func NewGetReportIPTrustNotFound() *GetReportIPTrustNotFound {
	return &GetReportIPTrustNotFound{}
}

/*
GetReportIPTrustNotFound describes a response with status code 404, with default header values.

If the machine is not found
*/
type GetReportIPTrustNotFound struct {
	Payload string
}

// IsSuccess returns true when this get report Ip trust not found response has a 2xx status code
func (o *GetReportIPTrustNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get report Ip trust not found response has a 3xx status code
func (o *GetReportIPTrustNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get report Ip trust not found response has a 4xx status code
func (o *GetReportIPTrustNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get report Ip trust not found response has a 5xx status code
func (o *GetReportIPTrustNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get report Ip trust not found response a status code equal to that given
func (o *GetReportIPTrustNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get report Ip trust not found response
func (o *GetReportIPTrustNotFound) Code() int {
	return 404
}

func (o *GetReportIPTrustNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /report/{ip}/trust][%d] getReportIpTrustNotFound %s", 404, payload)
}

func (o *GetReportIPTrustNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /report/{ip}/trust][%d] getReportIpTrustNotFound %s", 404, payload)
}

func (o *GetReportIPTrustNotFound) GetPayload() string {
	return o.Payload
}

func (o *GetReportIPTrustNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetReportIPTrustMethodNotAllowed creates a GetReportIPTrustMethodNotAllowed with default headers values
func NewGetReportIPTrustMethodNotAllowed() *GetReportIPTrustMethodNotAllowed {
	return &GetReportIPTrustMethodNotAllowed{}
}

/*
GetReportIPTrustMethodNotAllowed describes a response with status code 405, with default header values.

If the method is not allowed
*/
type GetReportIPTrustMethodNotAllowed struct {
	Payload string
}

// IsSuccess returns true when this get report Ip trust method not allowed response has a 2xx status code
func (o *GetReportIPTrustMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get report Ip trust method not allowed response has a 3xx status code
func (o *GetReportIPTrustMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get report Ip trust method not allowed response has a 4xx status code
func (o *GetReportIPTrustMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this get report Ip trust method not allowed response has a 5xx status code
func (o *GetReportIPTrustMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this get report Ip trust method not allowed response a status code equal to that given
func (o *GetReportIPTrustMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

// Code gets the status code for the get report Ip trust method not allowed response
func (o *GetReportIPTrustMethodNotAllowed) Code() int {
	return 405
}

func (o *GetReportIPTrustMethodNotAllowed) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /report/{ip}/trust][%d] getReportIpTrustMethodNotAllowed %s", 405, payload)
}

func (o *GetReportIPTrustMethodNotAllowed) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /report/{ip}/trust][%d] getReportIpTrustMethodNotAllowed %s", 405, payload)
}

func (o *GetReportIPTrustMethodNotAllowed) GetPayload() string {
	return o.Payload
}

func (o *GetReportIPTrustMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetReportIPTrustInternalServerError creates a GetReportIPTrustInternalServerError with default headers values
func NewGetReportIPTrustInternalServerError() *GetReportIPTrustInternalServerError {
	return &GetReportIPTrustInternalServerError{}
}

/*
GetReportIPTrustInternalServerError describes a response with status code 500, with default header values.

If there is a server error
*/
type GetReportIPTrustInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this get report Ip trust internal server error response has a 2xx status code
func (o *GetReportIPTrustInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get report Ip trust internal server error response has a 3xx status code
func (o *GetReportIPTrustInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get report Ip trust internal server error response has a 4xx status code
func (o *GetReportIPTrustInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get report Ip trust internal server error response has a 5xx status code
func (o *GetReportIPTrustInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get report Ip trust internal server error response a status code equal to that given
func (o *GetReportIPTrustInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get report Ip trust internal server error response
func (o *GetReportIPTrustInternalServerError) Code() int {
	return 500
}

func (o *GetReportIPTrustInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /report/{ip}/trust][%d] getReportIpTrustInternalServerError %s", 500, payload)
}

func (o *GetReportIPTrustInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /report/{ip}/trust][%d] getReportIpTrustInternalServerError %s", 500, payload)
}

func (o *GetReportIPTrustInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *GetReportIPTrustInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
