// Code generated by go-swagger; DO NOT EDIT.

package attestation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kommodity-io/kommodity-attestation-extension/pkg/openapi/attestation/attestationmodels"
)

// GetNonceReader is a Reader for the GetNonce structure.
type GetNonceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNonceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetNonceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetNonceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewGetNonceMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetNonceTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetNonceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /nonce] GetNonce", response, response.Code())
	}
}

// NewGetNonceOK creates a GetNonceOK with default headers values
func NewGetNonceOK() *GetNonceOK {
	return &GetNonceOK{}
}

/*
GetNonceOK describes a response with status code 200, with default header values.

OK
*/
type GetNonceOK struct {
	Payload *attestationmodels.NonceNonceResponse
}

// IsSuccess returns true when this get nonce o k response has a 2xx status code
func (o *GetNonceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get nonce o k response has a 3xx status code
func (o *GetNonceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get nonce o k response has a 4xx status code
func (o *GetNonceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get nonce o k response has a 5xx status code
func (o *GetNonceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get nonce o k response a status code equal to that given
func (o *GetNonceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get nonce o k response
func (o *GetNonceOK) Code() int {
	return 200
}

func (o *GetNonceOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nonce][%d] getNonceOK %s", 200, payload)
}

func (o *GetNonceOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nonce][%d] getNonceOK %s", 200, payload)
}

func (o *GetNonceOK) GetPayload() *attestationmodels.NonceNonceResponse {
	return o.Payload
}

func (o *GetNonceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(attestationmodels.NonceNonceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetNonceBadRequest creates a GetNonceBadRequest with default headers values
func NewGetNonceBadRequest() *GetNonceBadRequest {
	return &GetNonceBadRequest{}
}

/*
GetNonceBadRequest describes a response with status code 400, with default header values.

If the request is invalid
*/
type GetNonceBadRequest struct {
	Payload string
}

// IsSuccess returns true when this get nonce bad request response has a 2xx status code
func (o *GetNonceBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get nonce bad request response has a 3xx status code
func (o *GetNonceBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get nonce bad request response has a 4xx status code
func (o *GetNonceBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get nonce bad request response has a 5xx status code
func (o *GetNonceBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get nonce bad request response a status code equal to that given
func (o *GetNonceBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get nonce bad request response
func (o *GetNonceBadRequest) Code() int {
	return 400
}

func (o *GetNonceBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nonce][%d] getNonceBadRequest %s", 400, payload)
}

func (o *GetNonceBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nonce][%d] getNonceBadRequest %s", 400, payload)
}

func (o *GetNonceBadRequest) GetPayload() string {
	return o.Payload
}

func (o *GetNonceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetNonceMethodNotAllowed creates a GetNonceMethodNotAllowed with default headers values
func NewGetNonceMethodNotAllowed() *GetNonceMethodNotAllowed {
	return &GetNonceMethodNotAllowed{}
}

/*
GetNonceMethodNotAllowed describes a response with status code 405, with default header values.

If the method is not allowed
*/
type GetNonceMethodNotAllowed struct {
	Payload string
}

// IsSuccess returns true when this get nonce method not allowed response has a 2xx status code
func (o *GetNonceMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get nonce method not allowed response has a 3xx status code
func (o *GetNonceMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get nonce method not allowed response has a 4xx status code
func (o *GetNonceMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this get nonce method not allowed response has a 5xx status code
func (o *GetNonceMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this get nonce method not allowed response a status code equal to that given
func (o *GetNonceMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

// Code gets the status code for the get nonce method not allowed response
func (o *GetNonceMethodNotAllowed) Code() int {
	return 405
}

func (o *GetNonceMethodNotAllowed) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nonce][%d] getNonceMethodNotAllowed %s", 405, payload)
}

func (o *GetNonceMethodNotAllowed) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nonce][%d] getNonceMethodNotAllowed %s", 405, payload)
}

func (o *GetNonceMethodNotAllowed) GetPayload() string {
	return o.Payload
}

func (o *GetNonceMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetNonceTooManyRequests creates a GetNonceTooManyRequests with default headers values
func NewGetNonceTooManyRequests() *GetNonceTooManyRequests {
	return &GetNonceTooManyRequests{}
}

/*
GetNonceTooManyRequests describes a response with status code 429, with default header values.

If the rate limit is exceeded
*/
type GetNonceTooManyRequests struct {
	Payload string
}

// IsSuccess returns true when this get nonce too many requests response has a 2xx status code
func (o *GetNonceTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get nonce too many requests response has a 3xx status code
func (o *GetNonceTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get nonce too many requests response has a 4xx status code
func (o *GetNonceTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get nonce too many requests response has a 5xx status code
func (o *GetNonceTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get nonce too many requests response a status code equal to that given
func (o *GetNonceTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the get nonce too many requests response
func (o *GetNonceTooManyRequests) Code() int {
	return 429
}

func (o *GetNonceTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nonce][%d] getNonceTooManyRequests %s", 429, payload)
}

func (o *GetNonceTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nonce][%d] getNonceTooManyRequests %s", 429, payload)
}

func (o *GetNonceTooManyRequests) GetPayload() string {
	return o.Payload
}

func (o *GetNonceTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetNonceInternalServerError creates a GetNonceInternalServerError with default headers values
func NewGetNonceInternalServerError() *GetNonceInternalServerError {
	return &GetNonceInternalServerError{}
}

/*
GetNonceInternalServerError describes a response with status code 500, with default header values.

If there is a server error
*/
type GetNonceInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this get nonce internal server error response has a 2xx status code
func (o *GetNonceInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get nonce internal server error response has a 3xx status code
func (o *GetNonceInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get nonce internal server error response has a 4xx status code
func (o *GetNonceInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get nonce internal server error response has a 5xx status code
func (o *GetNonceInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get nonce internal server error response a status code equal to that given
func (o *GetNonceInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get nonce internal server error response
func (o *GetNonceInternalServerError) Code() int {
	return 500
}

func (o *GetNonceInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nonce][%d] getNonceInternalServerError %s", 500, payload)
}

func (o *GetNonceInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nonce][%d] getNonceInternalServerError %s", 500, payload)
}

func (o *GetNonceInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *GetNonceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
