// Code generated by go-swagger; DO NOT EDIT.

package attestation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetNonceParams creates a new GetNonceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNonceParams() *GetNonceParams {
	return &GetNonceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNonceParamsWithTimeout creates a new GetNonceParams object
// with the ability to set a timeout on a request.
func NewGetNonceParamsWithTimeout(timeout time.Duration) *GetNonceParams {
	return &GetNonceParams{
		timeout: timeout,
	}
}

// NewGetNonceParamsWithContext creates a new GetNonceParams object
// with the ability to set a context for a request.
func NewGetNonceParamsWithContext(ctx context.Context) *GetNonceParams {
	return &GetNonceParams{
		Context: ctx,
	}
}

// NewGetNonceParamsWithHTTPClient creates a new GetNonceParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNonceParamsWithHTTPClient(client *http.Client) *GetNonceParams {
	return &GetNonceParams{
		HTTPClient: client,
	}
}

/*
GetNonceParams contains all the parameters to send to the API endpoint

	for the get nonce operation.

	Typically these are written to a http.Request.
*/
type GetNonceParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get nonce params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNonceParams) WithDefaults() *GetNonceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get nonce params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNonceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get nonce params
func (o *GetNonceParams) WithTimeout(timeout time.Duration) *GetNonceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get nonce params
func (o *GetNonceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get nonce params
func (o *GetNonceParams) WithContext(ctx context.Context) *GetNonceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get nonce params
func (o *GetNonceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get nonce params
func (o *GetNonceParams) WithHTTPClient(client *http.Client) *GetNonceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get nonce params
func (o *GetNonceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetNonceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
