// Code generated by go-swagger; DO NOT EDIT.

package attestation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kommodity-io/kommodity-attestation-extension/pkg/openapi/attestation/attestationmodels"
)

// GetNounceReader is a Reader for the GetNounce structure.
type GetNounceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNounceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetNounceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetNounceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewGetNounceMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetNounceTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetNounceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /nounce] GetNounce", response, response.Code())
	}
}

// NewGetNounceOK creates a GetNounceOK with default headers values
func NewGetNounceOK() *GetNounceOK {
	return &GetNounceOK{}
}

/*
GetNounceOK describes a response with status code 200, with default header values.

OK
*/
type GetNounceOK struct {
	Payload *attestationmodels.NounceNounceResponse
}

// IsSuccess returns true when this get nounce o k response has a 2xx status code
func (o *GetNounceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get nounce o k response has a 3xx status code
func (o *GetNounceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get nounce o k response has a 4xx status code
func (o *GetNounceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get nounce o k response has a 5xx status code
func (o *GetNounceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get nounce o k response a status code equal to that given
func (o *GetNounceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get nounce o k response
func (o *GetNounceOK) Code() int {
	return 200
}

func (o *GetNounceOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nounce][%d] getNounceOK %s", 200, payload)
}

func (o *GetNounceOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nounce][%d] getNounceOK %s", 200, payload)
}

func (o *GetNounceOK) GetPayload() *attestationmodels.NounceNounceResponse {
	return o.Payload
}

func (o *GetNounceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(attestationmodels.NounceNounceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetNounceBadRequest creates a GetNounceBadRequest with default headers values
func NewGetNounceBadRequest() *GetNounceBadRequest {
	return &GetNounceBadRequest{}
}

/*
GetNounceBadRequest describes a response with status code 400, with default header values.

If the request is invalid
*/
type GetNounceBadRequest struct {
	Payload string
}

// IsSuccess returns true when this get nounce bad request response has a 2xx status code
func (o *GetNounceBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get nounce bad request response has a 3xx status code
func (o *GetNounceBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get nounce bad request response has a 4xx status code
func (o *GetNounceBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get nounce bad request response has a 5xx status code
func (o *GetNounceBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get nounce bad request response a status code equal to that given
func (o *GetNounceBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get nounce bad request response
func (o *GetNounceBadRequest) Code() int {
	return 400
}

func (o *GetNounceBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nounce][%d] getNounceBadRequest %s", 400, payload)
}

func (o *GetNounceBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nounce][%d] getNounceBadRequest %s", 400, payload)
}

func (o *GetNounceBadRequest) GetPayload() string {
	return o.Payload
}

func (o *GetNounceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetNounceMethodNotAllowed creates a GetNounceMethodNotAllowed with default headers values
func NewGetNounceMethodNotAllowed() *GetNounceMethodNotAllowed {
	return &GetNounceMethodNotAllowed{}
}

/*
GetNounceMethodNotAllowed describes a response with status code 405, with default header values.

If the method is not allowed
*/
type GetNounceMethodNotAllowed struct {
	Payload string
}

// IsSuccess returns true when this get nounce method not allowed response has a 2xx status code
func (o *GetNounceMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get nounce method not allowed response has a 3xx status code
func (o *GetNounceMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get nounce method not allowed response has a 4xx status code
func (o *GetNounceMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this get nounce method not allowed response has a 5xx status code
func (o *GetNounceMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this get nounce method not allowed response a status code equal to that given
func (o *GetNounceMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

// Code gets the status code for the get nounce method not allowed response
func (o *GetNounceMethodNotAllowed) Code() int {
	return 405
}

func (o *GetNounceMethodNotAllowed) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nounce][%d] getNounceMethodNotAllowed %s", 405, payload)
}

func (o *GetNounceMethodNotAllowed) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nounce][%d] getNounceMethodNotAllowed %s", 405, payload)
}

func (o *GetNounceMethodNotAllowed) GetPayload() string {
	return o.Payload
}

func (o *GetNounceMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetNounceTooManyRequests creates a GetNounceTooManyRequests with default headers values
func NewGetNounceTooManyRequests() *GetNounceTooManyRequests {
	return &GetNounceTooManyRequests{}
}

/*
GetNounceTooManyRequests describes a response with status code 429, with default header values.

If the rate limit is exceeded
*/
type GetNounceTooManyRequests struct {
	Payload string
}

// IsSuccess returns true when this get nounce too many requests response has a 2xx status code
func (o *GetNounceTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get nounce too many requests response has a 3xx status code
func (o *GetNounceTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get nounce too many requests response has a 4xx status code
func (o *GetNounceTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get nounce too many requests response has a 5xx status code
func (o *GetNounceTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get nounce too many requests response a status code equal to that given
func (o *GetNounceTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the get nounce too many requests response
func (o *GetNounceTooManyRequests) Code() int {
	return 429
}

func (o *GetNounceTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nounce][%d] getNounceTooManyRequests %s", 429, payload)
}

func (o *GetNounceTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nounce][%d] getNounceTooManyRequests %s", 429, payload)
}

func (o *GetNounceTooManyRequests) GetPayload() string {
	return o.Payload
}

func (o *GetNounceTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetNounceInternalServerError creates a GetNounceInternalServerError with default headers values
func NewGetNounceInternalServerError() *GetNounceInternalServerError {
	return &GetNounceInternalServerError{}
}

/*
GetNounceInternalServerError describes a response with status code 500, with default header values.

If there is a server error
*/
type GetNounceInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this get nounce internal server error response has a 2xx status code
func (o *GetNounceInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get nounce internal server error response has a 3xx status code
func (o *GetNounceInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get nounce internal server error response has a 4xx status code
func (o *GetNounceInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get nounce internal server error response has a 5xx status code
func (o *GetNounceInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get nounce internal server error response a status code equal to that given
func (o *GetNounceInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get nounce internal server error response
func (o *GetNounceInternalServerError) Code() int {
	return 500
}

func (o *GetNounceInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nounce][%d] getNounceInternalServerError %s", 500, payload)
}

func (o *GetNounceInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nounce][%d] getNounceInternalServerError %s", 500, payload)
}

func (o *GetNounceInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *GetNounceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
