// Code generated by go-swagger; DO NOT EDIT.

package attestation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetNounceParams creates a new GetNounceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNounceParams() *GetNounceParams {
	return &GetNounceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNounceParamsWithTimeout creates a new GetNounceParams object
// with the ability to set a timeout on a request.
func NewGetNounceParamsWithTimeout(timeout time.Duration) *GetNounceParams {
	return &GetNounceParams{
		timeout: timeout,
	}
}

// NewGetNounceParamsWithContext creates a new GetNounceParams object
// with the ability to set a context for a request.
func NewGetNounceParamsWithContext(ctx context.Context) *GetNounceParams {
	return &GetNounceParams{
		Context: ctx,
	}
}

// NewGetNounceParamsWithHTTPClient creates a new GetNounceParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNounceParamsWithHTTPClient(client *http.Client) *GetNounceParams {
	return &GetNounceParams{
		HTTPClient: client,
	}
}

/*
GetNounceParams contains all the parameters to send to the API endpoint

	for the get nounce operation.

	Typically these are written to a http.Request.
*/
type GetNounceParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get nounce params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNounceParams) WithDefaults() *GetNounceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get nounce params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNounceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get nounce params
func (o *GetNounceParams) WithTimeout(timeout time.Duration) *GetNounceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get nounce params
func (o *GetNounceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get nounce params
func (o *GetNounceParams) WithContext(ctx context.Context) *GetNounceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get nounce params
func (o *GetNounceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get nounce params
func (o *GetNounceParams) WithHTTPClient(client *http.Client) *GetNounceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get nounce params
func (o *GetNounceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetNounceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
