// Code generated by go-swagger; DO NOT EDIT.

package attestation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostReportReader is a Reader for the PostReport structure.
type PostReportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostReportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostReportOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostReportBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostReportUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewPostReportMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostReportInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /report] PostReport", response, response.Code())
	}
}

// NewPostReportOK creates a PostReportOK with default headers values
func NewPostReportOK() *PostReportOK {
	return &PostReportOK{}
}

/*
PostReportOK describes a response with status code 200, with default header values.

No content
*/
type PostReportOK struct {
	Payload string
}

// IsSuccess returns true when this post report o k response has a 2xx status code
func (o *PostReportOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post report o k response has a 3xx status code
func (o *PostReportOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post report o k response has a 4xx status code
func (o *PostReportOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post report o k response has a 5xx status code
func (o *PostReportOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post report o k response a status code equal to that given
func (o *PostReportOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post report o k response
func (o *PostReportOK) Code() int {
	return 200
}

func (o *PostReportOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /report][%d] postReportOK %s", 200, payload)
}

func (o *PostReportOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /report][%d] postReportOK %s", 200, payload)
}

func (o *PostReportOK) GetPayload() string {
	return o.Payload
}

func (o *PostReportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostReportBadRequest creates a PostReportBadRequest with default headers values
func NewPostReportBadRequest() *PostReportBadRequest {
	return &PostReportBadRequest{}
}

/*
PostReportBadRequest describes a response with status code 400, with default header values.

If the request is invalid
*/
type PostReportBadRequest struct {
	Payload string
}

// IsSuccess returns true when this post report bad request response has a 2xx status code
func (o *PostReportBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post report bad request response has a 3xx status code
func (o *PostReportBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post report bad request response has a 4xx status code
func (o *PostReportBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post report bad request response has a 5xx status code
func (o *PostReportBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post report bad request response a status code equal to that given
func (o *PostReportBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post report bad request response
func (o *PostReportBadRequest) Code() int {
	return 400
}

func (o *PostReportBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /report][%d] postReportBadRequest %s", 400, payload)
}

func (o *PostReportBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /report][%d] postReportBadRequest %s", 400, payload)
}

func (o *PostReportBadRequest) GetPayload() string {
	return o.Payload
}

func (o *PostReportBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostReportUnauthorized creates a PostReportUnauthorized with default headers values
func NewPostReportUnauthorized() *PostReportUnauthorized {
	return &PostReportUnauthorized{}
}

/*
PostReportUnauthorized describes a response with status code 401, with default header values.

If the nounce is invalid
*/
type PostReportUnauthorized struct {
	Payload string
}

// IsSuccess returns true when this post report unauthorized response has a 2xx status code
func (o *PostReportUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post report unauthorized response has a 3xx status code
func (o *PostReportUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post report unauthorized response has a 4xx status code
func (o *PostReportUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post report unauthorized response has a 5xx status code
func (o *PostReportUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post report unauthorized response a status code equal to that given
func (o *PostReportUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post report unauthorized response
func (o *PostReportUnauthorized) Code() int {
	return 401
}

func (o *PostReportUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /report][%d] postReportUnauthorized %s", 401, payload)
}

func (o *PostReportUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /report][%d] postReportUnauthorized %s", 401, payload)
}

func (o *PostReportUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *PostReportUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostReportMethodNotAllowed creates a PostReportMethodNotAllowed with default headers values
func NewPostReportMethodNotAllowed() *PostReportMethodNotAllowed {
	return &PostReportMethodNotAllowed{}
}

/*
PostReportMethodNotAllowed describes a response with status code 405, with default header values.

If the method is not allowed
*/
type PostReportMethodNotAllowed struct {
	Payload string
}

// IsSuccess returns true when this post report method not allowed response has a 2xx status code
func (o *PostReportMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post report method not allowed response has a 3xx status code
func (o *PostReportMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post report method not allowed response has a 4xx status code
func (o *PostReportMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this post report method not allowed response has a 5xx status code
func (o *PostReportMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this post report method not allowed response a status code equal to that given
func (o *PostReportMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

// Code gets the status code for the post report method not allowed response
func (o *PostReportMethodNotAllowed) Code() int {
	return 405
}

func (o *PostReportMethodNotAllowed) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /report][%d] postReportMethodNotAllowed %s", 405, payload)
}

func (o *PostReportMethodNotAllowed) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /report][%d] postReportMethodNotAllowed %s", 405, payload)
}

func (o *PostReportMethodNotAllowed) GetPayload() string {
	return o.Payload
}

func (o *PostReportMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostReportInternalServerError creates a PostReportInternalServerError with default headers values
func NewPostReportInternalServerError() *PostReportInternalServerError {
	return &PostReportInternalServerError{}
}

/*
PostReportInternalServerError describes a response with status code 500, with default header values.

If there is a server error
*/
type PostReportInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this post report internal server error response has a 2xx status code
func (o *PostReportInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post report internal server error response has a 3xx status code
func (o *PostReportInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post report internal server error response has a 4xx status code
func (o *PostReportInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post report internal server error response has a 5xx status code
func (o *PostReportInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post report internal server error response a status code equal to that given
func (o *PostReportInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post report internal server error response
func (o *PostReportInternalServerError) Code() int {
	return 500
}

func (o *PostReportInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /report][%d] postReportInternalServerError %s", 500, payload)
}

func (o *PostReportInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /report][%d] postReportInternalServerError %s", 500, payload)
}

func (o *PostReportInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *PostReportInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
