// Code generated by go-swagger; DO NOT EDIT.

package attestation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kommodity-io/kommodity-attestation-extension/pkg/openapi/attestation/attestationmodels"
)

// NewPostReportParams creates a new PostReportParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostReportParams() *PostReportParams {
	return &PostReportParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostReportParamsWithTimeout creates a new PostReportParams object
// with the ability to set a timeout on a request.
func NewPostReportParamsWithTimeout(timeout time.Duration) *PostReportParams {
	return &PostReportParams{
		timeout: timeout,
	}
}

// NewPostReportParamsWithContext creates a new PostReportParams object
// with the ability to set a context for a request.
func NewPostReportParamsWithContext(ctx context.Context) *PostReportParams {
	return &PostReportParams{
		Context: ctx,
	}
}

// NewPostReportParamsWithHTTPClient creates a new PostReportParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostReportParamsWithHTTPClient(client *http.Client) *PostReportParams {
	return &PostReportParams{
		HTTPClient: client,
	}
}

/*
PostReportParams contains all the parameters to send to the API endpoint

	for the post report operation.

	Typically these are written to a http.Request.
*/
type PostReportParams struct {

	/* Payload.

	   Report
	*/
	Payload *attestationmodels.ReportAttestationReportRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post report params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostReportParams) WithDefaults() *PostReportParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post report params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostReportParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post report params
func (o *PostReportParams) WithTimeout(timeout time.Duration) *PostReportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post report params
func (o *PostReportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post report params
func (o *PostReportParams) WithContext(ctx context.Context) *PostReportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post report params
func (o *PostReportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post report params
func (o *PostReportParams) WithHTTPClient(client *http.Client) *PostReportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post report params
func (o *PostReportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPayload adds the payload to the post report params
func (o *PostReportParams) WithPayload(payload *attestationmodels.ReportAttestationReportRequest) *PostReportParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the post report params
func (o *PostReportParams) SetPayload(payload *attestationmodels.ReportAttestationReportRequest) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *PostReportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
